"use client";
import Navbar from "@/core/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Mukta } from "next/font/google";
import { useState, useMemo, useEffect } from "react";
import { ILocationInfo } from "@/core/model/location.model";
import { LocationContext } from "@/core/context";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Mukta({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:
    "Order food online from India's best food delivery service. Order from restaurants near you",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [locationInfo, setLocationInfo] = useState<ILocationInfo | null>(null);

  const locationInfoState = useMemo(
    () => ({
      locationInfo,
      setLocationInfo,
    }),
    [locationInfo]
  );

  useEffect(() => {
    if (localStorage.userLocation) {
      const userLocation = JSON.parse(
        localStorage.getItem("userLocation") as string
      );
      setLocationInfo(userLocation);
    }
  }, []);
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <LocationContext.Provider value={locationInfoState}>
            <div className="w-full h-full bg-white flex flex-col">
              <Navbar />
              {children}
            </div>
          </LocationContext.Provider>
        </body>
      </UserProvider>
    </html>
  );
}
